version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: circuitverse_development
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NON_ROOT_USER_ID=${CURRENT_UID}
        - NON_ROOT_GROUP_ID=${CURRENT_GID}
    command: sleep infinity
    volumes:
      - .:/circuitverse:rw
      - ./config/database.docker.yml:/circuitverse/config/database.yml:rw
      - ruby_bundle:/usr/local/bundle:rw
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3035:3035"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CIRCUITVERSE_USE_SOLR: "false"
      DOCKER_ENVIRONMENT: "true"
      NODE_ENV: "development"
  redis:
    image: redis:7.0-alpine
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  ruby_bundle:
  postgres_data: